'use client'

export default function PrivacyPage() {
  return (
    <div style={{ minHeight: '100vh', background: '#060606', color: '#fff', fontFamily: 'monospace' }}>
      <nav style={{ padding: '0 24px', height: 52, display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid #0f0f0f', position: 'sticky', top: 0, background: '#060606', zIndex: 100 }}>
        <a href="/" style={{ textDecoration: 'none', fontSize: 13, fontWeight: 700 }}>
          <span style={{ color: '#fff' }}>FCP</span><span style={{ color: '#dc2626' }}>DIGITAL</span>
        </a>
        <a href="/" style={{ color: '#333', fontSize: 9, letterSpacing: '0.15em', textDecoration: 'none' }}>← BACK</a>
      </nav>
      <div style={{ maxWidth: 760, margin: '0 auto', padding: '60px 24px' }}>
        <div style={{ color: '#333', fontSize: 8, letterSpacing: '0.25em', marginBottom: 12 }}>LEGAL</div>
        <h1 style={{ color: '#fff', fontSize: 28, fontWeight: 700, marginBottom: 8 }}>Privacy Policy</h1>
        <div style={{ color: '#333', fontSize: 10, marginBottom: 48 }}>Last updated: March 2026</div>
        {[
          { title: 'Information We Collect', body: 'We collect information you provide directly to us when you sign up for our services, including your name, business name, email address, and phone number. We also collect information about how you use our services, including call logs, transcripts, and usage data associated with your account.' },
          { title: 'How We Use Your Information', body: 'We use the information we collect to provide, maintain, and improve our services, to process transactions, to send you technical notices and support messages, and to respond to your comments and questions. We may also use your information to send you marketing communications, though you may opt out at any time.' },
          { title: 'SMS Communications', body: 'By providing your mobile phone number and opting in through our consent form, you agree to receive SMS notifications from FCP Digital related to inbound call alerts, captured lead information, and call summaries generated by our AI receptionist platform.\n\nMessage frequency varies depending on call activity on your account. Message and data rates may apply depending on your mobile carrier. You may opt out of SMS notifications at any time by replying STOP to any message. For assistance, reply HELP or contact us at services@fcpdigital.net.\n\nMobile information and SMS opt-in data will not be shared, sold, or disclosed to third parties or affiliates for marketing or promotional purposes.' },
          { title: 'Call Recording and Transcripts', body: 'Our AI receptionist service records and transcribes calls made to your business phone number. These recordings and transcripts are stored securely and made available to you through your dashboard. By using our service, you are responsible for ensuring callers are properly notified of recording as required by applicable law in your jurisdiction.' },
          { title: 'Information Sharing', body: 'We do not sell, trade, or rent your personal information to third parties. We may share your information with trusted service providers who assist us in operating our platform, including cloud infrastructure providers and communication service providers, subject to confidentiality agreements.' },
          { title: 'Data Security', body: 'We implement industry-standard security measures to protect your information. All data is encrypted in transit and at rest. However, no method of transmission over the internet is 100% secure and we cannot guarantee absolute security.' },
          { title: 'Data Retention', body: 'We retain your account information for as long as your account is active. Call recordings and transcripts are retained for 90 days by default. You may request deletion of your data at any time by contacting us at services@fcpdigital.net.' },
          { title: 'Your Rights', body: 'You have the right to access, update, or delete your personal information at any time. You may also request a copy of the data we hold about you. To exercise these rights, contact us at services@fcpdigital.net.' },
          { title: 'Changes to This Policy', body: 'We may update this privacy policy from time to time. We will notify you of any significant changes by email or through a notice on our website. Your continued use of our services after such changes constitutes your acceptance of the updated policy.' },
          { title: 'Contact Us', body: 'If you have questions about this privacy policy, please contact us at services@fcpdigital.net or +1 313 327 3170.' },
        ].map((s, i) => (
          <div key={i} style={{ marginBottom: 40 }}>
            <div style={{ color: '#dc2626', fontSize: 9, letterSpacing: '0.2em', marginBottom: 10 }}>{'0' + (i + 1)}</div>
            <h2 style={{ color: '#fff', fontSize: 15, fontWeight: 700, marginBottom: 12 }}>{s.title}</h2>
            <p style={{ color: '#555', fontSize: 12, lineHeight: 1.9, margin: 0 }}>{s.body}</p>
          </div>
        ))}

        <div style={{ marginTop: 60, paddingTop: 40, borderTop: '1px solid #0f0f0f' }}>
          <div style={{ display: 'flex', gap: 20, justifyContent: 'center', flexWrap: 'wrap' as const }}>
            <a href="/terms" style={{ color: '#dc2626', fontSize: 9, letterSpacing: '0.1em', textDecoration: 'none' }}>TERMS & CONDITIONS</a>
            <span style={{ color: '#2a2a2a' }}>|</span>
            <a href="/sms-terms" style={{ color: '#dc2626', fontSize: 9, letterSpacing: '0.1em', textDecoration: 'none' }}>SMS TERMS</a>
          </div>
        </div>
      </div>
    </div>
  )
}
