'use client'

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-black py-24 px-6">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold text-white mb-2">
          Privacy Policy
        </h1>
        <p className="text-gray-400 mb-12">Last updated: February 10, 2026</p>

        <div className="space-y-8 text-gray-300">
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">1. Information We Collect</h2>
            <div className="space-y-4">
              <div>
                <h3 className="font-semibold text-white mb-2">Account Information:</h3>
                <ul className="list-disc list-inside space-y-1 ml-4">
                  <li>Business name, email address, phone number</li>
                  <li>Billing and payment information</li>
                  <li>Account settings and preferences</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-white mb-2">Call Data:</h3>
                <ul className="list-disc list-inside space-y-1 ml-4">
                  <li>Incoming call information (caller name, number)</li>
                  <li>Call recordings (audio)</li>
                  <li>Call transcripts (generated by AI)</li>
                  <li>Call metadata (duration, timestamp)</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-white mb-2">Technical Information:</h3>
                <ul className="list-disc list-inside space-y-1 ml-4">
                  <li>IP address and browser information</li>
                  <li>Usage analytics (which features you use)</li>
                  <li>Device information</li>
                </ul>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">2. How We Use Your Information</h2>
            <p className="mb-4">We use your information to:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Provide and maintain the FCP Digital service</li>
              <li>Process payments and billing</li>
              <li>Send service notifications and updates</li>
              <li>Respond to your support requests</li>
              <li>Improve our service and user experience</li>
              <li>Comply with legal obligations</li>
              <li>Prevent fraud and security issues</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">3. Data Storage & Retention</h2>
            <div className="space-y-4">
              <div>
                <h3 className="font-semibold text-white mb-2">Call Recordings:</h3>
                <ul className="list-disc list-inside space-y-1 ml-4">
                  <li><strong>Starter Plan:</strong> 90 days</li>
                  <li><strong>Professional Plan:</strong> 180 days</li>
                  <li><strong>Enterprise Plan:</strong> 365 days</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-white mb-2">Account Data:</h3>
                <p className="ml-4">Stored for the duration of your subscription + 30 days after cancellation</p>
              </div>
              <div>
                <h3 className="font-semibold text-white mb-2">Data Location:</h3>
                <p className="ml-4">All data stored in USA-based servers with encryption at rest and in transit</p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">4. Third-Party Services</h2>
            <p className="mb-4">We use trusted third-party providers for:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li><strong>Twilio:</strong> Phone number provisioning</li>
              <li><strong>Vapi:</strong> AI call handling</li>
              <li><strong>Stripe:</strong> Payment processing</li>
              <li><strong>Supabase:</strong> Database storage</li>
            </ul>
            <p className="mt-4">These providers have their own privacy policies and data handling practices. We recommend reviewing them.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">5. Data Security</h2>
            <p className="mb-4">We protect your data with:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>256-bit SSL/TLS encryption in transit</li>
              <li>AES-256 encryption at rest</li>
              <li>Regular security audits and penetration testing</li>
              <li>Secure authentication with two-factor options</li>
              <li>Limited access to data (employee access control)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">6. Your Rights (GDPR, CCPA, TCPA)</h2>
            <p className="mb-4">You have the right to:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li><strong>Access:</strong> Request a copy of your data</li>
              <li><strong>Correction:</strong> Update inaccurate information</li>
              <li><strong>Deletion:</strong> Request data deletion (with exceptions)</li>
              <li><strong>Portability:</strong> Export your data in machine-readable format</li>
              <li><strong>Opt-out:</strong> Opt out of marketing communications</li>
              <li><strong>Do Not Sell:</strong> We never sell your data</li>
            </ul>
            <p className="mt-4">To exercise these rights, contact us at <a href="mailto:privacy@fcpdigital.net" className="text-red-600 hover:text-red-500 underline">privacy@fcpdigital.net</a></p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">7. TCPA Compliance</h2>
            <p className="mb-4">FCP Digital is TCPA-compliant. We:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Maintain a Do-Not-Call list for contacted numbers</li>
              <li>Honor opt-out requests immediately</li>
              <li>Never use auto-dialers for marketing</li>
              <li>Only call during business hours (with exceptions for emergencies)</li>
              <li>Provide clear identification in all calls</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">8. Children's Privacy</h2>
            <p>FCP Digital is not intended for users under 18. We do not knowingly collect data from children. If we discover we have collected data from a child, we will delete it immediately.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">9. Cookies & Tracking</h2>
            <p className="mb-4">We use cookies for:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Session management (keeping you logged in)</li>
              <li>Security (preventing fraud)</li>
              <li>Analytics (understanding how you use FCP Digital)</li>
            </ul>
            <p className="mt-4">You can disable cookies in your browser, but this may limit functionality.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">10. Changes to This Policy</h2>
            <p>We may update this privacy policy periodically. We'll notify you via email of significant changes. Your continued use of FCP Digital constitutes acceptance of the updated policy.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">11. Contact Us</h2>
            <p className="mb-4">Questions about our privacy practices?</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Email: <a href="mailto:privacy@fcpdigital.net" className="text-red-600 hover:text-red-500 underline">privacy@fcpdigital.net</a></li>
              <li>Mailing Address: FCP Digital, Austin, TX, USA</li>
              <li>Data Protection Officer: <a href="mailto:dpo@fcpdigital.net" className="text-red-600 hover:text-red-500 underline">dpo@fcpdigital.net</a></li>
            </ul>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-gray-800">
          <a href="/" className="text-red-600 hover:text-red-500 underline">
            ← Back to Home
          </a>
        </div>
      </div>
    </div>
  )
}
